name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.bun/install/cache
          node_modules
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-
    
    - name: Install dependencies
      run: bun install --frozen-lockfile
    
    - name: Run tests
      run: bun test
    
    - name: Type check
      run: bun run typecheck
    
    - name: Build
      run: bun run build
    
    - name: Verify build output
      run: |
        test -f dist/main.js
        test -f dist/main.cjs
        test -x dist/main.js
        head -n 1 dist/main.js | grep -q "#!/usr/bin/env node"
    
    - name: Test with Node.js
      run: |
        # Test in proxy-only mode (doesn't spawn claude)
        PROXY_ONLY=true timeout 2s node dist/main.js || true
        # Check that proxy started successfully
        PROXY_ONLY=true node dist/main.js 2>&1 | grep -q "Proxy only mode"